name: clang-tidy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ 'rc-*', 'master' ]

jobs:
  tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy build-essential

      - uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.0.3'

      - name: Run clang-tidy
        run: make tidy
